import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Todo App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{/* Todo */}
				Create a Todo app interface, refer provided screenshots for
				design.
			</main>
		</div>
	);
}
